/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cactus({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cactus.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.14, 0, -0.02]} scale={0}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.clay2} />
        <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.spine} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.section} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.stable} />
      </group>
      <group position={[-0.06, 0, -0.19]} scale={0}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.clay3} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={nodes.Mesh001_1.material} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['spine.001']} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials['section.001']} />
        <mesh geometry={nodes.Mesh001_4.geometry} material={materials['stable.001']} />
      </group>
      <group position={[-0.08, 0, 0.14]} scale={0}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials.clay1} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={nodes.Mesh002_1.material} />
        <mesh geometry={nodes.Mesh002_2.geometry} material={materials['spine.003']} />
        <mesh geometry={nodes.Mesh002_3.geometry} material={materials['section.002']} />
        <mesh geometry={nodes.Mesh002_4.geometry} material={materials['stable.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/cactus.gltf')
